### ISSUE TITLE
Add rtx binary if eget and pkgx packages are not available

### ISSUE THREAD

**Issue by shah** [udi-service/udi-service#2]
See [rtx](https://github.com/jdx/rtx) and add that binary to the default packages. `rtx` is useful as a single-binary replacement for `asdf` in case eget and pkgx do not support a specified package.

**Comment by rinshadka** [comment]
@shah , Since we have used home polyglot as the base structure and "rtx" binary is already included in the .eget.toml file, rtx binary is available in UDIaaS deployment. I assume no further action needed here.

```
╰─ $ cat .eget.toml | grep rtx
["jdxcode/rtx"]
  udi_repo_url = "https://github.com/jdxcode/rtx"
  udi_doctor_cmd = "echo \"rtx `rtx --version`\""
```

```
╰─ $ udi-doctor | grep rtx
rtx 2023.11.0 linux-x64 (2796c45 2023-11-02)
```
Thanks.

**Comment by shah** [comment]
Yes, that works. The main thing to consider is that in case `pkgx` or `eget` packages are not available we should use `rtx` in the scripts to get packages and updates.
